// react/umi-learn/src/pages/admin/login.js
import React,{useRef,useEffect} from 'react';
import {useNavigate } from "umi";

function Login(props) {
    const loginId = useRef();
    const loginPwd = useRef();
    const navigate = useNavigate ();
    function  onHandleLogin(){
        if(loginPwd.current.value === "123456"){
            localStorage.setItem("umiLoginId",loginId.current.value);
            navigate("/welcome")
        }else{
            alert("密码 / 账号错误！")
        }
    }

    return (
        <div>
            <p>
                用户名：<input type="text" ref={loginId} />
            </p>
            <p>
                密码：<input type="password" ref={loginPwd}/>
            </p>
            <p>
                <button onClick={onHandleLogin}>登录</button>
            </p>
        </div>
    );
}

export default Login;

// node/exprecss/client/src/views/Login/index.vue
<template>
	<div class="login-container">
		<div class="form-container">
			<p>
				<label
					>账号:
					<input type="text" v-model="loginId" />
				</label>
			</p>
			<p>
				<label
					>密码:
					<input type="password" v-model="loginPwd" />
				</label>
			</p>
			<button @click="onHandleLogin">登录</button>
		</div>
	</div>
</template>

<script>
export default {
	data() {
		return {
			loginId: "",
			loginPwd: "",
		};
	},
	methods: {
		async onHandleLogin() {
            if(!this.loginId || !this.loginPwd){
                alert('请填写完整信息！');
                return;
            }
			const res = await this.$store.dispatch("userLogin/login", {
				loginId: this.loginId,
				loginPwd: this.loginPwd,
			});
            if(res) {
                setTimeout(()=>{
                    this.$router.push({name:'Home'})
                },1000)
            }else{
                alert('账号密码错误！')
            }
		},
	},
};
</script>

<style scoped >
</style>
